# fly.toml app configuration file generated for piano-vanilla-autumn-paper-398 on 2024-09-10T22:24:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'piano-vanilla-autumn-paper-398'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
